CI: Retry Download and extract prebuilt llvm step
In case the Download and extract prebuilt llvm step fails rerun it
again. Lately it is often failing like this:
```
2025-08-08 23:12:40 (67.4 MB/s) - ‘sha256sums’ saved [10079047/10079047]

gpg: assuming signed data in 'sha256sums'
gpg: Signature made Fri 08 Aug 2025 10:12:51 AM UTC
gpg:                using EDDSA key 92C561DE55AE6552F3C736B82B0151090606D1D9
gpg: BAD signature from "OpenWrt Build System (Nitrokey3) <contact@openwrt.org>" [unknown]
Error: Process completed with exit code 1.
```

Print the hash of the files for better debugging.

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>